import Head from "next/head";
import Image from "next/image";

import LayoutWithTransition from "@/components/LayoutWithTransition";
import Beach from "@/public/beach.jpg";

export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutWithTransition>
        <main className="h-screen flex items-center">
          <header className="max-w-5xl mx-auto space-y-10">
            <Image src={Beach} alt="beach" className="w-1/2" />
            <h1 className="text-6xl font-bold max-w-3xl">About Page</h1>
            <p className="text-xl max-w-2xl">
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Voluptatum optio totam voluptate nam repudiandae magni voluptas
              aspernatur aperiam laudantium earum, nemo, nihil non autem itaque
              veniam ipsam aliquam! Quae ex in inventore adipisci autem vel ea
              molestiae architecto, vitae dolore natus pariatur quisquam labore
              perspiciatis voluptates sequi tempore possimus aut.
            </p>
          </header>
        </main>
      </LayoutWithTransition>
    </>
  );
}
